name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        env:
          CGO_ENABLED: "0"
        run: go build -v ./...

      - name: Test
        env:
          CGO_ENABLED: "0"
        run: go test -timeout=60s ./...
